# Generated by Django 2.2.7 on 2019-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sweater'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
